github.com:
    user: scudzy
    git_protocol: https
    users:
        scudzy:
            oauth_token: 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
    oauth_token: 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
