github.com:
    user: scudzy
    git_protocol: https
    users:
        scudzy:
            oauth_token: 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
    oauth_token: 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
