#!/usr/bin/env zsh

# execution time
function tm() {
  local start=$(date +%s%N)
  $@
  local end=$(date +%s%N)
  local exit_code=$?
  local total=$end-$start
    echo ""
    echo -e "Took \e[1;32m$((total/1000000))\e[0m ms. Exit code ${exit_code}."
  return $exit_code
}
